server {
    listen 80;
#name of the server
    server_name localhost;
#Nginx serves your React build files.
    root /usr/share/nginx/html;
    index index.html;
#This ensures React Router works (SPA routing).
    location / {
        try_files $uri /index.html;
    }
#her the magic line wen clint vist flowers localhsot port 80 it forowrded to backend
    location /api/ {
        proxy_pass http://backend-service:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }  
}
