apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

spec:
  replicas: {{ .Values.frontend.replicaCount }}
#selector is how the other obejec find tag
  selector:
    matchLabels:
      app: frontend
# label is just a tag put on kubrnetes object
  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        
        ports:
        - containerPort: 80
